window.APP_CONFIG = {
  APPWRITE_ENDPOINT: 'https://cloud.appwrite.io/v1',
  APPWRITE_PROJECT_ID: '',
  APPWRITE_DATABASE_ID: '',
  APPWRITE_COLLECTION_ID: '',
  APPWRITE_BUCKET_ID: '',
  APPWRITE_ADMIN_TEAM_ID: '',
};
